#### Snakefile for Ega-Cryptor Application ####

# Load Configuration File
configfile: "config/configfile.yaml"

# Get values from configuration file
input_path = config["input"]
output_path = config["output"]
ega_cryptor_path = config["path_to_ega"]

# Load rules
include: "rules/ega_cryptor.smk"

rule all:
    input:
        finish_file = (f'{output_path}/finished.txt')
    shell:
        """
        echo "I just run subrules!"
        """ 